[tools]
go = "1.24.2"
golangci-lint = "v2.7.2"
goreleaser = "2.13.1"
opentofu = "1.9.0"

[env]
PROJECT_NAME = "{{ config_root | basename }}"

[hooks]
enter = [
  'echo ""',
  'echo "[MISE] Setup $PROJECT_NAME project..."',
  #
  'mise i -q',
  #
  'pre-commit install -f --hook-type pre-commit',
]
